name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build project
      run: |
        # Si tu as un build step, sinon ignore
        echo "No build step for Flask"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: az-webapp-tpdevops
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_az-webapp-tpdevops }}
        package: .
